version: '3'
services:
  omnipay-cobrefacil:
    build:
      args:
        user: ${USER}
        uid: ${UID}
      context: .
      dockerfile: Dockerfile
    image: omnipay-cobrefacil
    container_name: omnipay-cobrefacil
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
